### Teste para todas as salas
GET http://localhost:40000/getAllSalas
Accept: application/json

### Teste para inserir uma nova sala
POST http://localhost:40000/insertSalas
Content-Type: application/json

{
    "descricao": "Sala B",
    "localizacao": "Bloco B",
    "capacidade": 30,
    "removido": false
}

### Teste para buscar uma sala por ID
GET http://localhost:40000/getSalasByID/1
Accept: application/json

### Teste para atualizar uma sala
PUT http://localhost:40000/updateSalas/1
Content-Type: application/json

{
    "descricao": "Sala A Atualizada",
    "localizacao": "Bloco A",
    "capacidade": 35
}

### Teste para remover uma sala
DELETE http://localhost:40000/deleteSalas/1
Accept: application/json